name: Deploy VitePress site to Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24 # Обновили до актуальной Node.js 24
          cache: npm

      - name: Setup Pages
        uses: actions/configure-pages@v5 # Обновили версию экшена до v5

      - name: Install dependencies
        run: npm ci

      - name: Build with VitePress
        # Добавляем флаг --no-ignore-dead-links, чтобы сборка не падала из-за битых ссылок
        run: npx vitepress build --no-ignore-dead-links 

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .vitepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4